# Generated by Django 3.2 on 2024-11-26 08:23

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=15, null=True, unique=True)),
                ('name', models.CharField(max_length=12)),
                ('department', models.IntegerField(blank=True, choices=[(0, '資訊科學系'), (1, '外系')], null=True)),
                ('identity', models.IntegerField(choices=[(0, '大學部'), (1, '管理員'), (2, '日間碩士班'), (3, '碩士在職專班'), (4, '系辦工讀生')], default=0)),
                ('enrollYear', models.DecimalField(decimal_places=0, default=2024, max_digits=4)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='StudentDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualifiedId', models.BooleanField(default=False)),
                ('evaluationForm', models.BooleanField(default=False)),
                ('assesmentResult', models.BooleanField(default=False)),
                ('confirmation', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('professor', models.CharField(max_length=5)),
                ('postDate', models.DateField(blank=True, null=True)),
                ('state', models.IntegerField(choices=[(0, '已申請'), (1, '已取消')], default=0)),
                ('cancelapplication', models.FileField(blank=True, default=None, null=True, upload_to='CancelProposal/')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('report', models.FileField(default=None, upload_to='Report/')),
                ('poster', models.ImageField(default=None, upload_to='Poster/')),
                ('professor', models.CharField(max_length=5)),
                ('field', models.IntegerField(choices=[(0, '軟體開發及程式設計'), (1, '網路及多媒體應用'), (2, '系統及演算法開發')], default=0)),
                ('postDate', models.DateField(blank=True, null=True)),
                ('letter', models.FileField(blank=True, default=None, null=True, upload_to='Uploaded Files/')),
                ('post', models.PositiveIntegerField(blank=True, choices=[(0, '研討會'), (1, '期刊')], default=0, null=True)),
                ('seminarDate', models.DateTimeField(blank=True, null=True)),
                ('seminarName', models.CharField(blank=True, max_length=20, null=True)),
                ('journalNumber', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('state', models.IntegerField(choices=[(0, '專題'), (1, '已申請'), (2, '已取消')], default=0)),
                ('cancelapplication', models.FileField(blank=True, default=None, null=True, upload_to='CancelFinal/')),
                ('selected', models.BooleanField(default=False)),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='student.proposal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barCode', models.CharField(max_length=20, null=True)),
                ('lendTimes', models.IntegerField(default=0)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.project')),
            ],
            options={
                'ordering': ['barCode', 'project__user__identity'],
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('acqDate', models.DateField(default=django.utils.timezone.now)),
                ('organizer', models.CharField(max_length=30)),
                ('level', models.CharField(choices=[('A', 'A'), ('B', 'B')], default=0, max_length=1)),
                ('pazz', models.IntegerField(choices=[(0, '審核中'), (1, '通過'), (2, '未通過')], default=0)),
                ('image', models.ImageField(default=None, upload_to='image/')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username', 'level'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('underTaker', models.CharField(blank=True, max_length=10, null=True)),
                ('state', models.IntegerField(choices=[(0, '已預約'), (1, '已借閱'), (2, '已歸還')], default=0)),
                ('bookingDate', models.DateTimeField(null=True)),
                ('takingDate', models.DateTimeField(blank=True, null=True)),
                ('paper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='student.paper')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='student.year')),
            ],
            options={
                'ordering': ['state', '-id'],
            },
        ),
    ]
