# Generated by Django 3.2 on 2023-02-17 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='graduateLevel',
            field=models.DecimalField(decimal_places=0, default=2027, max_digits=4),
        ),
    ]
