# Generated by Django 3.2 on 2023-02-24 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20230224_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='graduateLevel',
        ),
    ]
