# Generated by Django 3.2 on 2023-02-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20230228_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='username',
            field=models.CharField(default='', max_length=12),
        ),
    ]
