# Generated by Django 3.2 on 2023-02-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_proposal_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='author',
            field=models.CharField(default='', max_length=12),
        ),
    ]
