# Generated by Django 3.2 on 2023-03-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_booking_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='state',
            field=models.IntegerField(choices=[(0, '已預約'), (1, '已借閱')], default=0),
        ),
    ]
