# Generated by Django 3.2 on 2023-03-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_booking_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='type',
            field=models.IntegerField(choices=[(0, '日碩論文'), (1, '職碩論文'), (2, '大學部專題報告書')], default=0),
        ),
    ]
