# Generated by Django 3.2 on 2023-03-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_booking_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='type',
            field=models.IntegerField(choices=[(0, '日碩論文'), (1, '職碩論文')], default=0),
        ),
    ]
