# Generated by Django 3.2 on 2023-03-06 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_proposal_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=30)),
                ('type', models.IntegerField(choices=[(0, '日間碩士班論文'), (1, '碩士在職專班論文'), (2, '大學部專題報告書')], default=0)),
                ('professor', models.CharField(max_length=12)),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username']},
        ),
        migrations.AlterField(
            model_name='booking',
            name='type',
            field=models.IntegerField(choices=[(0, '日間碩士班論文'), (1, '碩士在職專班論文'), (2, '大學部專題報告書')], default=0),
        ),
        migrations.AlterField(
            model_name='license',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='type',
            field=models.IntegerField(choices=[(0, '日間碩士班'), (1, '碩士在職專班')], default=0),
        ),
    ]
