# Generated by Django 3.2 on 2023-03-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_paper_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='barCode',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
