# Generated by Django 3.2 on 2023-03-13 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_booking_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bookingTime',
            field=models.TimeField(default=datetime.datetime(2023, 3, 13, 19, 26, 48, 965321)),
        ),
    ]
