# Generated by Django 3.2 on 2023-03-13 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_booking_bookingtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='barCode',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='bookingTime',
            field=models.TimeField(default=datetime.datetime(2023, 3, 13, 20, 4, 40, 514147)),
        ),
    ]
