# Generated by Django 3.2 on 2023-03-16 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_auto_20230314_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='code',
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.IntegerField(choices=[(0, '軟體開發及程式設計'), (1, '網路及多媒體應用')], default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='bookingTime',
            field=models.TimeField(default=datetime.datetime(2023, 3, 16, 20, 37, 0, 881106)),
        ),
    ]
