# Generated by Django 3.2 on 2023-03-16 13:55

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_auto_20230316_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bookingDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='booking',
            name='bookingTime',
            field=models.TimeField(default=datetime.datetime(2023, 3, 16, 21, 55, 25, 651332)),
        ),
    ]
