# Generated by Django 3.2 on 2023-03-16 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_auto_20230316_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='type',
            new_name='filed',
        ),
        migrations.AlterField(
            model_name='booking',
            name='bookingTime',
            field=models.TimeField(default=datetime.datetime(2023, 3, 16, 22, 2, 24, 888708)),
        ),
    ]
