# Generated by Django 3.2 on 2023-03-16 14:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_auto_20230316_2202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='license',
            options={'ordering': ['user__username', 'level']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['user']},
        ),
        migrations.RenameField(
            model_name='license',
            old_name='owner',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='paper',
            old_name='username',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='owner',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='author',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='barCode',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='paperName',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='type',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='username',
        ),
        migrations.RemoveField(
            model_name='license',
            name='username',
        ),
        migrations.RemoveField(
            model_name='project',
            name='username',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='username',
        ),
        migrations.AddField(
            model_name='booking',
            name='paper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='student.paper'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposal',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='bookingTime',
            field=models.TimeField(default=datetime.datetime(2023, 3, 16, 22, 32, 35, 68928)),
        ),
    ]
