# Generated by Django 3.2 on 2023-03-16 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_auto_20230316_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='filed',
            new_name='field',
        ),
        migrations.AlterField(
            model_name='booking',
            name='bookingTime',
            field=models.TimeField(default=datetime.datetime(2023, 3, 16, 22, 38, 19, 964963)),
        ),
    ]
