# Generated by Django 3.2 on 2023-03-17 05:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0022_auto_20230316_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='takingDate',
            field=models.DateField(default=datetime.datetime(2023, 3, 17, 5, 36, 47, 336212, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='bookingDate',
            field=models.DateField(default=datetime.datetime(2023, 3, 17, 5, 36, 47, 336212, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='bookingTime',
            field=models.TimeField(default=datetime.datetime(2023, 3, 17, 13, 36, 47, 336212)),
        ),
    ]
