# Generated by Django 3.2 on 2023-03-21 09:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0023_auto_20230317_1336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['state', '-id']},
        ),
        migrations.RemoveField(
            model_name='paper',
            name='author',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='name',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='type',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='journalNumber',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='letter',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='post',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='postProof',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='seminarDate',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='seminarName',
        ),
        migrations.AddField(
            model_name='paper',
            name='lendTimes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paper',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='student.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='journalNumber',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='letter',
            field=models.FileField(blank=True, default=None, null=True, upload_to='Uploaded Files/'),
        ),
        migrations.AddField(
            model_name='project',
            name='post',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '研討會'), (1, '期刊')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='postDate',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='postProof',
            field=models.FileField(blank=True, default=None, null=True, upload_to='image/'),
        ),
        migrations.AddField(
            model_name='project',
            name='proposal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='student.proposal'),
        ),
        migrations.AddField(
            model_name='project',
            name='seminarDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='seminarName',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.IntegerField(choices=[(0, '大學部'), (1, '日間碩士班'), (2, '碩士在職專班')], default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='bookingDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='bookingTime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='state',
            field=models.IntegerField(choices=[(0, '已預約'), (1, '已借閱'), (2, '已歸還')], default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='takingDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='type',
            field=models.IntegerField(choices=[(1, '日間碩士班'), (2, '碩士在職專班')], default=0),
        ),
    ]
