# Generated by Django 3.2 on 2023-03-25 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0026_auto_20230324_1204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paper',
            options={'ordering': ['barCode', 'project__type']},
        ),
        migrations.AddField(
            model_name='booking',
            name='underTaker',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
