# Generated by Django 3.2 on 2023-03-25 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0027_auto_20230325_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='bookingTime',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='takingTime',
        ),
        migrations.AlterField(
            model_name='booking',
            name='bookingDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='takingDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
