# Generated by Django 3.2 on 2023-03-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0029_auto_20230325_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.IntegerField(choices=[(0, '資訊科學系'), (1, '外系')], default=1),
            preserve_default=False,
        ),
    ]
