# Generated by Django 3.2 on 2023-04-24 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0032_auto_20230328_2120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='year',
            options={'ordering': ['year']},
        ),
        migrations.AddField(
            model_name='project',
            name='state',
            field=models.IntegerField(choices=[(0, '專題'), (1, '已申請'), (2, '已取消')], default=0),
        ),
    ]
