# Generated by Django 3.2 on 2023-04-24 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0033_auto_20230424_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cancelapplication',
            field=models.FileField(blank=True, default=None, null=True, upload_to='Cancel/'),
        ),
    ]
