# Generated by Django 3.2 on 2023-04-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0036_alter_project_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='state',
            field=models.IntegerField(choices=[(0, '已申請'), (1, '已取消')], default=0),
        ),
    ]
