# Generated by Django 3.2 on 2023-04-25 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0037_proposal_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
