# Generated by Django 3.2 on 2023-04-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0038_alter_proposal_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='graduateLevel',
        ),
        migrations.AddField(
            model_name='user',
            name='enrollYear',
            field=models.DecimalField(decimal_places=0, default=2023, max_digits=4),
        ),
    ]
