# Generated by Django 3.2 on 2023-04-26 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0039_auto_20230425_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='cancelapplication',
            field=models.FileField(blank=True, default=None, null=True, upload_to='CancelProposal/'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cancelapplication',
            field=models.FileField(blank=True, default=None, null=True, upload_to='CancelFinal/'),
        ),
    ]
