# Generated by Django 3.2 on 2023-04-28 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0040_auto_20230426_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identity',
            field=models.IntegerField(choices=[(0, '大學部'), (1, '管理員'), (2, '日間碩士班'), (3, '碩士在職專班')], default=0),
        ),
    ]
