# Generated by Django 3.2 on 2023-04-28 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0041_alter_user_identity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paper',
            options={'ordering': ['barCode', 'project__user__identity']},
        ),
        migrations.RemoveField(
            model_name='project',
            name='type',
        ),
    ]
