# Generated by Django 3.2 on 2023-05-10 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0042_auto_20230428_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='type',
        ),
    ]
