# Generated by Django 3.2 on 2023-05-24 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0044_alter_user_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualifiedId', models.BooleanField(default=False)),
                ('evaluationForm', models.BooleanField(default=False)),
                ('assesmentResult', models.BooleanField(default=False)),
                ('confirmation', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
