# Generated by Django 3.2 on 2023-05-24 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0045_studentdoc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdoc',
            old_name='evaluationForm',
            new_name='evalutionForm',
        ),
    ]
