# Generated by Django 3.2 on 2023-05-24 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0046_rename_evaluationform_studentdoc_evalutionform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdoc',
            old_name='evalutionForm',
            new_name='evaluationForm',
        ),
    ]
